# Generated by Django 5.1.4 on 2024-12-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="totalmatch",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="totalwins",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
