# Generated by Django 5.1.4 on 2024-12-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player1", models.CharField(max_length=100)),
                ("player2", models.CharField(max_length=100)),
                ("winner", models.CharField(blank=True, max_length=100, null=True)),
                ("match_date", models.DateTimeField(auto_now_add=True)),
                ("round", models.IntegerField()),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="Tournament.tournament",
                    ),
                ),
            ],
        ),
    ]
